[package]
name = "biji-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Biji Note command-line interface"

[dependencies]
biji-core = { path = "../biji-core" }
clap = { version = "4", features = ["derive"] }
log = "0.4"
chrono = "0.4"
dirs-next = "2"
env_logger = "0.11"
uuid = { version = "1", features = ["v4"] }
